version: '1'

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    user: postgres
    env_file:
      - ./nipa_test_backend/.env
    ports:
      - 5432:5432
    volumes:
      - ./nipa_test_backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
        context: ./nipa_test_backend
        dockerfile: ./dockerfile.prod
    restart: on-failure
    env_file:
      - ./nipa_test_backend/.env
    ports:
      - 3002:3002
    depends_on:
      postgres:
        condition: service_healthy
    # links:
    #   - postgres
    networks:
      - backend-network
    # volumes:
    #   - ./nipa_test_backend:/app

  frontend:
    build:
      context: ./nipa_test_front
      dockerfile: ./dockerfile.prod
    env_file:
      - ./nipa_test_front/.env
    ports:
      - 3000:3000
    depends_on:
      - backend
    links:
      - backend

networks:
    backend-network:
        driver: bridge